junit_tests(
  name='jarjar',
  sources=rglobs('*.java'),
  resources=[
    'src/test:generics-precompiled',
  ],
  dependencies=[
    'lib:asm',
    'lib:junit',
    'src/main/org/pantsbuild/jarjar',
  ]
)

