jar_library(
  name='asm',
  jars=[
    jar('org.ow2.asm', 'asm', '6.2'),
  ]
)

jar_library(
  name='asm-commons',
  jars=[
    jar('org.ow2.asm', 'asm-commons', '6.2'),
  ]
)

jar_library(
  name='ant',
  jars=[
    jar('org.apache.ant', 'ant', '1.9.9'),
  ]
)

jar_library(
  name='maven-plugin-api',
  jars=[
    jar('org.apache.maven', 'maven-plugin-api', '3.3.9'),
  ]
)

jar_library(
  name='junit',
  jars=[
    jar('junit', 'junit', '4.12'),
  ]
)

jar_library(
  name='commons-lang3',
  jars=[
    jar('org.apache.commons', 'commons-lang3', '3.7'),
  ]
)
