jar_library(
  name='asm',
  jars=[
    jar('org.ow2.asm', 'asm', '4.0'),
  ]
)

jar_library(
  name='asm-commons',
  jars=[
    jar('org.ow2.asm', 'asm-commons', '4.0'),
  ]
)

jar_library(
  name='ant',
  jars=[
    jar('org.apache.ant', 'ant', '1.9.6'),
  ]
)

jar_library(
  name='maven-plugin-api',
  jars=[
    jar('org.apache.maven', 'maven-plugin-api', '3.3.3'),
  ]
)

jar_library(
  name='junit',
  jars=[
    jar('junit', 'junit', '4.12'),
  ]
)
