junit_tests(
  dependencies=[
    'lib:asm',
    'lib:junit',
    'src/main/java/org/pantsbuild/jarjar',
    'src/test/java/org/pantsbuild/jarjar/integration',
    'src/test/java/org/pantsbuild/jarjar/example',
    'src/test:generics-precompiled',
  ]
)

